
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import config from '@/config';

const SUPABASE_URL = config.supabase.url;
const SUPABASE_ANON_KEY = config.supabase.anonKey;

// Configure the Supabase client with enhanced security settings (PKCE flow and sessionStorage)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: sessionStorage, // Use sessionStorage instead of localStorage for better security
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Content-Security-Policy': "default-src 'self'; script-src 'self'; object-src 'none';"
    },
  }
});

// Add environment configuration constants for the other services
export const ENABLE_CLOUDINARY = config.features.enableCloudinary;
